'use strict';

/**
 * Topology domains: a domain is a connected component of the cascade link
 * graph. Domains are derived (never stored), so the domain set can never
 * drift from the actual links. Roles remain pure operator state: roled but
 * disconnected nodes are staged assets and belong to no domain.
 *
 * Domain key: the lexicographically smallest node id of the component —
 * deterministic for a given component. Keys change when components merge or
 * split, which is acceptable because the graph itself changed then.
 */

function entityId(entity) {
    const value = entity !== null && typeof entity === 'object'
        ? entity.id ?? entity._id ?? entity.nodeId
        : entity;
    return value === null || value === undefined ? null : String(value);
}

function linkEndpoints(link) {
    return [
        entityId(link?.source ?? link?.portalNode),
        entityId(link?.target ?? link?.bridgeNode),
    ];
}

/**
 * @param {Array} nodes - node docs (or minimal {id|_id, role|cascadeRole, name})
 * @param {Array} links - link docs (or minimal {source/portalNode, target/bridgeNode})
 * @returns {Array<{key:string, nodeIds:string[], linkIds:string[], label:string,
 *                  portals:string[], relays:string[], bridges:string[]}>}
 *          domains sorted by key; links referencing unknown nodes are ignored.
 */
function computeTopologyDomains({ nodes = [], links = [] } = {}) {
    const nodesById = new Map();
    for (const node of nodes) {
        const id = entityId(node);
        if (id) nodesById.set(id, node);
    }

    const adjacency = new Map(); // nodeId -> [{ other, linkId }]
    const linkIdsByNode = new Map();
    for (const link of links) {
        const linkId = entityId(link);
        const [source, target] = linkEndpoints(link);
        if (!linkId || !source || !target) continue;
        if (!nodesById.has(source) || !nodesById.has(target)) continue;
        if (!adjacency.has(source)) adjacency.set(source, []);
        if (!adjacency.has(target)) adjacency.set(target, []);
        adjacency.get(source).push({ other: target, linkId });
        adjacency.get(target).push({ other: source, linkId });
        if (!linkIdsByNode.has(source)) linkIdsByNode.set(source, new Set());
        if (!linkIdsByNode.has(target)) linkIdsByNode.set(target, new Set());
        linkIdsByNode.get(source).add(linkId);
        linkIdsByNode.get(target).add(linkId);
    }

    const visited = new Set();
    const domains = [];
    for (const startId of adjacency.keys()) {
        if (visited.has(startId)) continue;
        const componentNodes = [];
        const componentLinks = new Set();
        const queue = [startId];
        visited.add(startId);
        while (queue.length > 0) {
            const current = queue.shift();
            componentNodes.push(current);
            for (const linkId of linkIdsByNode.get(current) || []) componentLinks.add(linkId);
            for (const edge of adjacency.get(current) || []) {
                if (visited.has(edge.other)) continue;
                visited.add(edge.other);
                queue.push(edge.other);
            }
        }
        componentNodes.sort((left, right) => left.localeCompare(right, 'en'));
        const byRole = { portal: [], relay: [], bridge: [] };
        for (const nodeId of componentNodes) {
            const role = nodesById.get(nodeId)?.role ?? nodesById.get(nodeId)?.cascadeRole;
            if (byRole[role]) byRole[role].push(nodeId);
        }
        domains.push({
            key: componentNodes[0],
            nodeIds: componentNodes,
            linkIds: [...componentLinks].sort((left, right) => left.localeCompare(right, 'en')),
            portals: byRole.portal,
            relays: byRole.relay,
            bridges: byRole.bridge,
        });
    }

    domains.sort((left, right) => left.key.localeCompare(right.key, 'en'));
    for (const domain of domains) domain.label = domainLabel(domain, nodesById);
    return domains;
}

function nodeName(nodesById, nodeId) {
    const node = nodesById.get(nodeId);
    return typeof node?.name === 'string' && node.name.length > 0 ? node.name : nodeId;
}

/**
 * Autogenerated human-readable label, e.g.
 * "Порталы A, B → бридж Z" / "Портал A → бридж Z".
 */
function domainLabel(domain, nodesById) {
    const names = ids => ids.map(id => nodeName(nodesById, id));
    const portals = names(domain.portals);
    const bridges = names(domain.bridges);
    const left = portals.length === 1 ? `Портал ${portals[0]}`
        : portals.length > 1 ? `Порталы ${portals.join(', ')}`
            : 'Без портала';
    const right = bridges.length === 1 ? `бридж ${bridges[0]}`
        : bridges.length > 1 ? `бриджи ${bridges.join(', ')}`
            : 'без бриджа';
    return `${left} → ${right}`;
}

/** The domain (connected component) containing nodeId, or null when staged. */
function domainOfNode(domains, nodeId) {
    const id = entityId(nodeId);
    if (!id) return null;
    return domains.find(domain => domain.nodeIds.includes(id)) || null;
}

/**
 * Slice a projected topology ({nodes, links, groups}) down to one domain.
 * Route groups survive only with paths whose linkIds stay inside the domain;
 * groups left without any path are dropped.
 */
function sliceTopologyToDomain(topology, domain) {
    const nodeIds = new Set(domain.nodeIds);
    const linkIds = new Set(domain.linkIds);
    const groups = [];
    for (const group of topology.groups || []) {
        const paths = (group.paths || []).filter(path => {
            const pathLinkIds = (path.linkIds || []).map(entityId);
            return pathLinkIds.length > 0 && pathLinkIds.every(id => linkIds.has(id));
        });
        if (paths.length > 0) groups.push({ ...group, paths });
    }
    return {
        nodes: (topology.nodes || []).filter(node => nodeIds.has(entityId(node))),
        links: (topology.links || []).filter(link => linkIds.has(entityId(link))),
        groups,
    };
}

module.exports = {
    computeTopologyDomains,
    domainOfNode,
    domainLabel,
    sliceTopologyToDomain,
};
